services:
  web:
    build: .
    env_file:
      - .env
    command: python /code/manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - .:/code
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db

  db:
    image: postgres:16.1-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
