# Generated by Django 5.0.3 on 2024-09-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
